Count,Message,Traceback,Nodes
1,"HTTPSConnectionPool(host='userapi.alms.crab.alemira.com', port=443): Max retries exceeded with url: /api/v1/users/me/roles (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))","  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/silvia/Projects/alemira-test/app/locusttasks/student_tasks.py"", line 40, in visit_my_courses
    student.visit_my_courses()
  File ""/Users/silvia/Projects/alemira-test/app/profiles/student.py"", line 49, in visit_my_courses
    self.users_api.get_user_roles(headers)
  File ""/Users/silvia/Projects/alemira-test/app/apis/users_api.py"", line 111, in get_user_roles
    if response.ok:
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 180, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 563, in send
    raise SSLError(e, request=request)
",local
1,"HTTPSConnectionPool(host='userapi.alms.crab.alemira.com', port=443): Max retries exceeded with url: /api/v1/activities/query?requireTotalCount=True&filter=%5B%22code%22%2C%22%3D%22%2C%22USI2%22%5D (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))","  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/silvia/Projects/alemira-test/app/locusttasks/instructor_tasks.py"", line 73, in upload_one_attachment_to_course_content
    instructor.upload_one_attachment_to_course_content()
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 112, in upload_one_attachment_to_course_content
    activity_to_upload_one_attachment = self._select_one_activity(headers)
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 243, in _select_one_activity
    res = self.activities_api.get_activities_by_query(
  File ""/Users/silvia/Projects/alemira-test/app/apis/activities_api.py"", line 39, in get_activities_by_query
    if response.ok:
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 180, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 563, in send
    raise SSLError(e, request=request)
",local
