Count,Message,Traceback,Nodes
3,Invalid URL '': No scheme supplied. Perhaps you meant http://?,"  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/locustfiles/locustfile_after_enroll.py"", line 110, in take_course
    self.student.take_course()
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 52, in take_course
    self._take_course(headers, me)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 96, in _take_course
    self._download_attachment(headers, objective.get_attachment_url())
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 103, in _download_attachment
    self.objectives_api.download_attachment_from_objective(headers, url)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/apis/objectives_api.py"", line 269, in download_attachment_from_objective
    headers=headers,
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 600, in get
    return self.request(""GET"", url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 135, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 368, in prepare
    self.prepare_url(url, params)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 439, in prepare_url
    raise MissingSchema(
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/locustfiles/locustfile_after_enroll.py"", line 110, in take_course
    self.student.take_course()
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 52, in take_course
    self._take_course(headers, me)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 87, in _take_course
    self._visit_course(headers, course, objective, user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 180, in _visit_course
    self.objective_workflow_aggregates_api.get_activity_with_aggregates_by_id(
  File ""/Users/ketai/Projects/alemira/alemira-test/app/apis/objective_workflow_aggregates_api.py"", line 71, in get_activity_with_aggregates_by_id
    if response.ok:
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/locustfiles/locustfile_after_enroll.py"", line 57, in edit_one_course_description
    self.instructor.edit_one_course_description()
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/instructor.py"", line 50, in edit_one_course_description
    objective_to_edit = self.select_one_objective(headers)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/instructor.py"", line 148, in select_one_objective
    objective = self._select_one_objective(headers)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/instructor.py"", line 154, in _select_one_objective
    res = self.objectives_api.get_objectives_by_query(
  File ""/Users/ketai/Projects/alemira/alemira-test/app/apis/objectives_api.py"", line 51, in get_objectives_by_query
    ) as response:
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/locustfiles/locustfile_after_enroll.py"", line 110, in take_course
    self.student.take_course()
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 51, in take_course
    me = self.lms_users_api.get_user_me(headers)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/apis/lms_users_api.py"", line 30, in get_user_me
    ) as response:
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/locustfiles/locustfile_after_enroll.py"", line 110, in take_course
    self.student.take_course()
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 52, in take_course
    self._take_course(headers, me)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 96, in _take_course
    self._download_attachment(headers, objective.get_attachment_url())
  File ""/Users/ketai/Projects/alemira/alemira-test/app/profiles/student.py"", line 103, in _download_attachment
    self.objectives_api.download_attachment_from_objective(headers, url)
  File ""/Users/ketai/Projects/alemira/alemira-test/app/apis/objectives_api.py"", line 275, in download_attachment_from_objective
    name=""download attachment from objective"",
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/ketai/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
