Count,Message,Traceback,Nodes
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/silvia/Projects/alemira-test/app/locusttasks/instructor_tasks.py"", line 55, in upload_one_attachment_to_course_description
    instructor.upload_one_attachment_to_course_description()
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 93, in upload_one_attachment_to_course_description
    self._upload_one_attachment_to_course_description(
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 145, in _upload_one_attachment_to_course_description
    self.objectives_api.upload_attachment_to_objective(
  File ""/Users/silvia/Projects/alemira-test/app/apis/objectives_api.py"", line 263, in upload_attachment_to_objective
    self.update_objective(headers, objective)
  File ""/Users/silvia/Projects/alemira-test/app/apis/objectives_api.py"", line 191, in update_objective
    updated_state = self.get_updated_objective_state_by_id(
  File ""/Users/silvia/Projects/alemira-test/app/apis/objectives_api.py"", line 96, in get_updated_objective_state_by_id
    if response.ok:
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 180, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 347, in run
    self.execute_next_task()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/user/task.py"", line 493, in execute_task
    task(self.user)
  File ""/Users/silvia/Projects/alemira-test/app/locusttasks/instructor_tasks.py"", line 31, in enroll_one_student
    instructor.enroll_one_student()
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 47, in enroll_one_student
    self._enroll_one_student(headers, objective_to_enroll)
  File ""/Users/silvia/Projects/alemira-test/app/profiles/instructor.py"", line 174, in _enroll_one_student
    self.personal_enrollments_api.create_personal_enrollment(
  File ""/Users/silvia/Projects/alemira-test/app/apis/personal_enrollments_api.py"", line 51, in create_personal_enrollment
    if response.ok:
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/models.py"", line 765, in ok
    self.raise_for_status()
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 23, in raise_for_status
    raise self.error
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/locust/clients.py"", line 180, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/silvia/miniconda3/envs/alemira/lib/python3.10/site-packages/requests/adapters.py"", line 547, in send
    raise ConnectionError(err, request=request)
",local
